# Generated by Django 6.1 on 2026-08-18 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_product_price_product_stock_quantity_issue_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workers', models.PositiveIntegerField(verbose_name='Assembler/Worker')),
                ('quantity_manufactured', models.PositiveIntegerField(verbose_name='Manufactured Per Day')),
                ('total_stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_records', to='website.product')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
