# Generated by Django 6.1 on 2026-08-18 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_manufacturingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workers', models.PositiveIntegerField(default=1)),
                ('quantity_manufactured', models.PositiveIntegerField()),
                ('total_stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing', to='website.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ManufacturingRecord',
        ),
    ]
