# Generated by Django 6.1 on 2026-08-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_manufacturing_delete_manufacturingrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_quantity',
            new_name='available_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='total_manufactured',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
