# Generated by Django 6.1 on 2026-08-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_worker_manufacturing_worker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['watt']},
        ),
        migrations.AddField(
            model_name='product',
            name='watt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
