# Generated by Django 6.1 on 2026-08-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_product_options_product_watt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturing',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
