# Generated by Django 6.1

import django.db.models.deletion
from django.db import migrations, models


def create_customers_and_link_issues(apps, schema_editor):

    Customer = apps.get_model('website', 'Customer')
    Issue = apps.get_model('website', 'Issue')

    for issue in Issue.objects.all():

        customer_name = issue.customer_name

        if not customer_name:
            continue

        customer_name = customer_name.strip()

        if not customer_name:
            continue

        customer, created = Customer.objects.get_or_create(
            name=customer_name
        )

        issue.customer_id = customer.id

        issue.save(
            update_fields=['customer']
        )


def reverse_customers(apps, schema_editor):

    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            'website',
            '0012_customer_issue_customer'
        ),
    ]

    operations = [

        # ==========================================
        # OLD CUSTOMER NAME -> CUSTOMER
        # ==========================================

        migrations.RunPython(
            create_customers_and_link_issues,
            reverse_customers
        ),

        # ==========================================
        # CUSTOMER ADDRESS
        # ==========================================

        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(
                blank=True
            ),
        ),

        # ==========================================
        # CUSTOMER PHONE
        # ==========================================

        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(
                max_length=15,
                blank=True
            ),
        ),

        # ==========================================
        # UNIQUE CUSTOMER NAME
        # ==========================================

        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(
                max_length=100,
                unique=True
            ),
        ),

        # ==========================================
        # CUSTOMER FOREIGN KEY
        # ==========================================

        migrations.AlterField(
            model_name='issue',
            name='customer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='issues',
                to='website.customer'
            ),
        ),

        # ==========================================
        # REMOVE OLD CUSTOMER NAME
        # ==========================================

        migrations.RemoveField(
            model_name='issue',
            name='customer_name',
        ),
    ]