# Generated by Django 6.1 on 2026-08-20 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_issue_customer_name_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_manufactured', models.PositiveIntegerField(default=0)),
                ('total_issued', models.PositiveIntegerField(default=0)),
                ('net_quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='net_quantity', to='website.product')),
            ],
        ),
    ]
