# Generated by Django 6.1 on 2026-08-20 07:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_distributor_issue_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='distributor',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
