# Generated by Django 6.1 on 2026-08-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='watt',
        ),
    ]
