# Generated by Django 6.1 on 2026-08-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_product_options_remove_product_watt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['watt']},
        ),
        migrations.AddField(
            model_name='product',
            name='watt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
