"""
Django settings for mytask project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
import cloudinary


# ==================================================
# BASE DIRECTORY
# ==================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / '.env')


# ==================================================
# SECURITY
# ==================================================

SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-development-key'
)

DEBUG = True

ALLOWED_HOSTS = ['*']


# ==================================================
# APPLICATIONS
# ==================================================

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Cloudinary
    'cloudinary',
    'cloudinary_storage',

    # Your App
    'website',
]


# ==================================================
# MIDDLEWARE
# ==================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==================================================
# URL CONFIGURATION
# ==================================================

ROOT_URLCONF = 'mytask.urls'


# ==================================================
# TEMPLATES
# ==================================================

TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


# ==================================================
# WSGI
# ==================================================

WSGI_APPLICATION = 'mytask.wsgi.application'


# ==================================================
# DATABASE
# ==================================================

DATABASES = {

    'default': dj_database_url.config(

        default='sqlite:///' + str(
            BASE_DIR / 'db.sqlite3'
        ),

        conn_max_age=600
    )
}


# ==================================================
# PASSWORD VALIDATION
# ==================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==================================================
# INTERNATIONALIZATION
# ==================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ==================================================
# STATIC FILES
# ==================================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# ==================================================
# CLOUDINARY
# ==================================================

CLOUDINARY_STORAGE = {

    'CLOUD_NAME': os.environ.get(
        'CLOUDINARY_CLOUD_NAME'
    ),

    'API_KEY': os.environ.get(
        'CLOUDINARY_API_KEY'
    ),

    'API_SECRET': os.environ.get(
        'CLOUDINARY_API_SECRET'
    ),
}


# Cloudinary configuration

cloudinary.config(

    cloud_name=os.environ.get(
        'CLOUDINARY_CLOUD_NAME'
    ),

    api_key=os.environ.get(
        'CLOUDINARY_API_KEY'
    ),

    api_secret=os.environ.get(
        'CLOUDINARY_API_SECRET'
    ),
)


DEFAULT_FILE_STORAGE = (
    'cloudinary_storage.storage.MediaCloudinaryStorage'
)


# ==================================================
# RESEND EMAIL CONFIGURATION
# ==================================================

RESEND_API_KEY = os.environ.get(
    'RESEND_API_KEY'
)


# ==================================================
# DEFAULT PRIMARY KEY
# ==================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'